### ISSUE TITLE
Colab Notebook Error

### ISSUE THREAD

**Issue by ericborgos** [xrsrke/toolformer#2]
Your Colab notebook gives this error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-5-08cc2a5d7772> in <module>
      2 from transformers import AutoModelForCausalLM, AutoTokenizer
      3 
----> 4 from toolformer.data_generator import DataGenerator
      5 from toolformer.api import CalculatorAPI, WolframeAPI
      6 from toolformer.prompt import calculator_prompt, wolframe_prompt

ModuleNotFoundError: No module named 'toolformer.data_generator'

**Comment by xrsrke** [comment]
Hi. I'm looking into it
