### ISSUE TITLE
how can I train a new model

### ISSUE THREAD

**Issue by Miusery** [xrsrke/toolformer#5]
hi, your work sounds awesome! Can I finetune a new model with your code (if I've already filtered api calls data )? Could you plz give me more details?  I‘ll really appreciate it!!

**Comment by fischhaber** [comment]
@paramuse did you figure out how to finetune a new model?

**Comment by xrsrke** [comment]
@fischhaber  @paramuse ToolFormer is used to generate API-augmented data. So, after generating the data, you can fine-tune it as normal
